language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
before_script:
    - composer self-update
    - composer install
    - composer require satooshi/php-coveralls
script:
    - phpunit
after_script:
  - php vendor/bin/coveralls -v
